import { expect, test } from '@playwright/test'

test('看板拖拽、编辑、主题及刷新持久化', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: '添加任务' }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await page.getByLabel('标题').fill('浏览器验证')
  await page.getByLabel('优先级', { exact: true }).selectOption('low')
  await page.getByRole('button', { name: '添加任务' }).click()
  const doing = page.locator('[data-status="doing"]')
  await page.locator('article').dragTo(doing)
  await expect(doing.locator('article')).toHaveCount(1)
  await page.reload()
  await expect(doing.locator('article')).toHaveCount(1)
  await page.getByRole('button', { name: '编辑：浏览器验证', exact: true }).click()
  await page.getByLabel('标题').fill('编辑草稿')
  await doing.locator('article').dragTo(page.locator('[data-status="done"]'))
  await page.getByRole('button', { name: '保存修改' }).click()
  await expect(page.locator('[data-status="done"] article')).toContainText('编辑草稿')
  await page.getByRole('button', { name: '深色模式' }).click()
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('[data-status="done"] article')).toContainText('编辑草稿')
  await expect(doing).toHaveCSS('background-color', 'rgb(27, 38, 32)')
  await page.screenshot({ path: 'test-results/board-dark.png', fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: '深色模式' }).click()
  await expect(doing).toHaveCSS('background-color', 'rgb(238, 238, 231)')
  await expect(page.locator('article h3')).toHaveCSS('color', 'rgb(36, 61, 53)')
  await page.screenshot({ path: 'test-results/board-light.png', fullPage: true, animations: 'disabled' })
  await page.setViewportSize({ width: 375, height: 812 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: '删除：编辑草稿', exact: true }).click()
  await page.reload()
  await expect(page.locator('article')).toHaveCount(0)
  expect(errors).toEqual([])
})
